// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj/paxos/Messages.proto

package paxos;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    PREPARE_REQUEST(0, 0),
    ACCEPT_REQUEST(1, 1),
    PROMISE(2, 2),
    ACCEPTED_PROPOSAL(3, 3),
    HEARTBEAT(4, 4),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Type valueOf(int value) {
      switch (value) {
        case 0: return PREPARE_REQUEST;
        case 1: return ACCEPT_REQUEST;
        case 2: return PROMISE;
        case 3: return ACCEPTED_PROPOSAL;
        case 4: return HEARTBEAT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return paxos.Messages.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Type[] VALUES = {
      PREPARE_REQUEST, ACCEPT_REQUEST, PROMISE, ACCEPTED_PROPOSAL, HEARTBEAT, 
    };
    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      paxos.Messages.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:Type)
  }
  
  public enum Role
      implements com.google.protobuf.ProtocolMessageEnum {
    PROPOSER(0, 0),
    ACCEPTOR(1, 1),
    LEARNER(2, 2),
    MONITOR(3, 4),
    TXSERVER(4, 5),
    TXCLIENT(5, 6),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Role valueOf(int value) {
      switch (value) {
        case 0: return PROPOSER;
        case 1: return ACCEPTOR;
        case 2: return LEARNER;
        case 4: return MONITOR;
        case 5: return TXSERVER;
        case 6: return TXCLIENT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Role>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Role>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Role>() {
            public Role findValueByNumber(int number) {
              return Role.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return paxos.Messages.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final Role[] VALUES = {
      PROPOSER, ACCEPTOR, LEARNER, MONITOR, TXSERVER, TXCLIENT, 
    };
    public static Role valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Role(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      paxos.Messages.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:Role)
  }
  
  public static final class Envelope extends
      com.google.protobuf.GeneratedMessage {
    // Use Envelope.newBuilder() to construct.
    private Envelope() {
      initFields();
    }
    private Envelope(boolean noInit) {}
    
    private static final Envelope defaultInstance;
    public static Envelope getDefaultInstance() {
      return defaultInstance;
    }
    
    public Envelope getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paxos.Messages.internal_static_Envelope_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paxos.Messages.internal_static_Envelope_fieldAccessorTable;
    }
    
    // required .Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private paxos.Messages.Type type_;
    public boolean hasType() { return hasType; }
    public paxos.Messages.Type getType() { return type_; }
    
    // required bytes payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private boolean hasPayload;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPayload() { return hasPayload; }
    public com.google.protobuf.ByteString getPayload() { return payload_; }
    
    // optional int32 pxId = 3;
    public static final int PXID_FIELD_NUMBER = 3;
    private boolean hasPxId;
    private int pxId_ = 0;
    public boolean hasPxId() { return hasPxId; }
    public int getPxId() { return pxId_; }
    
    private void initFields() {
      type_ = paxos.Messages.Type.PREPARE_REQUEST;
    }
    public final boolean isInitialized() {
      if (!hasType) return false;
      if (!hasPayload) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeEnum(1, getType().getNumber());
      }
      if (hasPayload()) {
        output.writeBytes(2, getPayload());
      }
      if (hasPxId()) {
        output.writeInt32(3, getPxId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getType().getNumber());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPayload());
      }
      if (hasPxId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getPxId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static paxos.Messages.Envelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Envelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Envelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Envelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Envelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Envelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Envelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Envelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(paxos.Messages.Envelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private paxos.Messages.Envelope result;
      
      // Construct using paxos.Messages.Envelope.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new paxos.Messages.Envelope();
        return builder;
      }
      
      protected paxos.Messages.Envelope internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new paxos.Messages.Envelope();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return paxos.Messages.Envelope.getDescriptor();
      }
      
      public paxos.Messages.Envelope getDefaultInstanceForType() {
        return paxos.Messages.Envelope.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public paxos.Messages.Envelope build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private paxos.Messages.Envelope buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public paxos.Messages.Envelope buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        paxos.Messages.Envelope returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof paxos.Messages.Envelope) {
          return mergeFrom((paxos.Messages.Envelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(paxos.Messages.Envelope other) {
        if (other == paxos.Messages.Envelope.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasPxId()) {
          setPxId(other.getPxId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              paxos.Messages.Type value = paxos.Messages.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 18: {
              setPayload(input.readBytes());
              break;
            }
            case 24: {
              setPxId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required .Type type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public paxos.Messages.Type getType() {
        return result.getType();
      }
      public Builder setType(paxos.Messages.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = paxos.Messages.Type.PREPARE_REQUEST;
        return this;
      }
      
      // required bytes payload = 2;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public com.google.protobuf.ByteString getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = getDefaultInstance().getPayload();
        return this;
      }
      
      // optional int32 pxId = 3;
      public boolean hasPxId() {
        return result.hasPxId();
      }
      public int getPxId() {
        return result.getPxId();
      }
      public Builder setPxId(int value) {
        result.hasPxId = true;
        result.pxId_ = value;
        return this;
      }
      public Builder clearPxId() {
        result.hasPxId = false;
        result.pxId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Envelope)
    }
    
    static {
      defaultInstance = new Envelope(true);
      paxos.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Envelope)
  }
  
  public static final class PrepareRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use PrepareRequest.newBuilder() to construct.
    private PrepareRequest() {
      initFields();
    }
    private PrepareRequest(boolean noInit) {}
    
    private static final PrepareRequest defaultInstance;
    public static PrepareRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PrepareRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paxos.Messages.internal_static_PrepareRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paxos.Messages.internal_static_PrepareRequest_fieldAccessorTable;
    }
    
    // required int32 n = 1;
    public static final int N_FIELD_NUMBER = 1;
    private boolean hasN;
    private int n_ = 0;
    public boolean hasN() { return hasN; }
    public int getN() { return n_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasN) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasN()) {
        output.writeInt32(1, getN());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasN()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getN());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static paxos.Messages.PrepareRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.PrepareRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.PrepareRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.PrepareRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.PrepareRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.PrepareRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.PrepareRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.PrepareRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.PrepareRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.PrepareRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(paxos.Messages.PrepareRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private paxos.Messages.PrepareRequest result;
      
      // Construct using paxos.Messages.PrepareRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new paxos.Messages.PrepareRequest();
        return builder;
      }
      
      protected paxos.Messages.PrepareRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new paxos.Messages.PrepareRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return paxos.Messages.PrepareRequest.getDescriptor();
      }
      
      public paxos.Messages.PrepareRequest getDefaultInstanceForType() {
        return paxos.Messages.PrepareRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public paxos.Messages.PrepareRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private paxos.Messages.PrepareRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public paxos.Messages.PrepareRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        paxos.Messages.PrepareRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof paxos.Messages.PrepareRequest) {
          return mergeFrom((paxos.Messages.PrepareRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(paxos.Messages.PrepareRequest other) {
        if (other == paxos.Messages.PrepareRequest.getDefaultInstance()) return this;
        if (other.hasN()) {
          setN(other.getN());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setN(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 n = 1;
      public boolean hasN() {
        return result.hasN();
      }
      public int getN() {
        return result.getN();
      }
      public Builder setN(int value) {
        result.hasN = true;
        result.n_ = value;
        return this;
      }
      public Builder clearN() {
        result.hasN = false;
        result.n_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PrepareRequest)
    }
    
    static {
      defaultInstance = new PrepareRequest(true);
      paxos.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PrepareRequest)
  }
  
  public static final class Proposal extends
      com.google.protobuf.GeneratedMessage {
    // Use Proposal.newBuilder() to construct.
    private Proposal() {
      initFields();
    }
    private Proposal(boolean noInit) {}
    
    private static final Proposal defaultInstance;
    public static Proposal getDefaultInstance() {
      return defaultInstance;
    }
    
    public Proposal getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paxos.Messages.internal_static_Proposal_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paxos.Messages.internal_static_Proposal_fieldAccessorTable;
    }
    
    // required int32 n = 1;
    public static final int N_FIELD_NUMBER = 1;
    private boolean hasN;
    private int n_ = 0;
    public boolean hasN() { return hasN; }
    public int getN() { return n_; }
    
    // required .CommitAttempt v = 2;
    public static final int V_FIELD_NUMBER = 2;
    private boolean hasV;
    private proto.RPCProtos.CommitAttempt v_;
    public boolean hasV() { return hasV; }
    public proto.RPCProtos.CommitAttempt getV() { return v_; }
    
    private void initFields() {
      v_ = proto.RPCProtos.CommitAttempt.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasN) return false;
      if (!hasV) return false;
      if (!getV().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasN()) {
        output.writeInt32(1, getN());
      }
      if (hasV()) {
        output.writeMessage(2, getV());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasN()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getN());
      }
      if (hasV()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getV());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static paxos.Messages.Proposal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Proposal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Proposal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Proposal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Proposal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Proposal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Proposal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Proposal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Proposal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Proposal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(paxos.Messages.Proposal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private paxos.Messages.Proposal result;
      
      // Construct using paxos.Messages.Proposal.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new paxos.Messages.Proposal();
        return builder;
      }
      
      protected paxos.Messages.Proposal internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new paxos.Messages.Proposal();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return paxos.Messages.Proposal.getDescriptor();
      }
      
      public paxos.Messages.Proposal getDefaultInstanceForType() {
        return paxos.Messages.Proposal.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public paxos.Messages.Proposal build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private paxos.Messages.Proposal buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public paxos.Messages.Proposal buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        paxos.Messages.Proposal returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof paxos.Messages.Proposal) {
          return mergeFrom((paxos.Messages.Proposal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(paxos.Messages.Proposal other) {
        if (other == paxos.Messages.Proposal.getDefaultInstance()) return this;
        if (other.hasN()) {
          setN(other.getN());
        }
        if (other.hasV()) {
          mergeV(other.getV());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setN(input.readInt32());
              break;
            }
            case 18: {
              proto.RPCProtos.CommitAttempt.Builder subBuilder = proto.RPCProtos.CommitAttempt.newBuilder();
              if (hasV()) {
                subBuilder.mergeFrom(getV());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setV(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 n = 1;
      public boolean hasN() {
        return result.hasN();
      }
      public int getN() {
        return result.getN();
      }
      public Builder setN(int value) {
        result.hasN = true;
        result.n_ = value;
        return this;
      }
      public Builder clearN() {
        result.hasN = false;
        result.n_ = 0;
        return this;
      }
      
      // required .CommitAttempt v = 2;
      public boolean hasV() {
        return result.hasV();
      }
      public proto.RPCProtos.CommitAttempt getV() {
        return result.getV();
      }
      public Builder setV(proto.RPCProtos.CommitAttempt value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasV = true;
        result.v_ = value;
        return this;
      }
      public Builder setV(proto.RPCProtos.CommitAttempt.Builder builderForValue) {
        result.hasV = true;
        result.v_ = builderForValue.build();
        return this;
      }
      public Builder mergeV(proto.RPCProtos.CommitAttempt value) {
        if (result.hasV() &&
            result.v_ != proto.RPCProtos.CommitAttempt.getDefaultInstance()) {
          result.v_ =
            proto.RPCProtos.CommitAttempt.newBuilder(result.v_).mergeFrom(value).buildPartial();
        } else {
          result.v_ = value;
        }
        result.hasV = true;
        return this;
      }
      public Builder clearV() {
        result.hasV = false;
        result.v_ = proto.RPCProtos.CommitAttempt.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Proposal)
    }
    
    static {
      defaultInstance = new Proposal(true);
      paxos.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Proposal)
  }
  
  public static final class Promise extends
      com.google.protobuf.GeneratedMessage {
    // Use Promise.newBuilder() to construct.
    private Promise() {
      initFields();
    }
    private Promise(boolean noInit) {}
    
    private static final Promise defaultInstance;
    public static Promise getDefaultInstance() {
      return defaultInstance;
    }
    
    public Promise getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paxos.Messages.internal_static_Promise_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paxos.Messages.internal_static_Promise_fieldAccessorTable;
    }
    
    // required int32 prepareN = 1;
    public static final int PREPAREN_FIELD_NUMBER = 1;
    private boolean hasPrepareN;
    private int prepareN_ = 0;
    public boolean hasPrepareN() { return hasPrepareN; }
    public int getPrepareN() { return prepareN_; }
    
    // optional .Proposal acceptedPreviously = 2;
    public static final int ACCEPTEDPREVIOUSLY_FIELD_NUMBER = 2;
    private boolean hasAcceptedPreviously;
    private paxos.Messages.Proposal acceptedPreviously_;
    public boolean hasAcceptedPreviously() { return hasAcceptedPreviously; }
    public paxos.Messages.Proposal getAcceptedPreviously() { return acceptedPreviously_; }
    
    private void initFields() {
      acceptedPreviously_ = paxos.Messages.Proposal.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasPrepareN) return false;
      if (hasAcceptedPreviously()) {
        if (!getAcceptedPreviously().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPrepareN()) {
        output.writeInt32(1, getPrepareN());
      }
      if (hasAcceptedPreviously()) {
        output.writeMessage(2, getAcceptedPreviously());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPrepareN()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getPrepareN());
      }
      if (hasAcceptedPreviously()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAcceptedPreviously());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static paxos.Messages.Promise parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Promise parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Promise parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Promise parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Promise parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Promise parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Promise parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Promise parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Promise parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Promise parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(paxos.Messages.Promise prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private paxos.Messages.Promise result;
      
      // Construct using paxos.Messages.Promise.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new paxos.Messages.Promise();
        return builder;
      }
      
      protected paxos.Messages.Promise internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new paxos.Messages.Promise();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return paxos.Messages.Promise.getDescriptor();
      }
      
      public paxos.Messages.Promise getDefaultInstanceForType() {
        return paxos.Messages.Promise.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public paxos.Messages.Promise build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private paxos.Messages.Promise buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public paxos.Messages.Promise buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        paxos.Messages.Promise returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof paxos.Messages.Promise) {
          return mergeFrom((paxos.Messages.Promise)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(paxos.Messages.Promise other) {
        if (other == paxos.Messages.Promise.getDefaultInstance()) return this;
        if (other.hasPrepareN()) {
          setPrepareN(other.getPrepareN());
        }
        if (other.hasAcceptedPreviously()) {
          mergeAcceptedPreviously(other.getAcceptedPreviously());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setPrepareN(input.readInt32());
              break;
            }
            case 18: {
              paxos.Messages.Proposal.Builder subBuilder = paxos.Messages.Proposal.newBuilder();
              if (hasAcceptedPreviously()) {
                subBuilder.mergeFrom(getAcceptedPreviously());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAcceptedPreviously(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 prepareN = 1;
      public boolean hasPrepareN() {
        return result.hasPrepareN();
      }
      public int getPrepareN() {
        return result.getPrepareN();
      }
      public Builder setPrepareN(int value) {
        result.hasPrepareN = true;
        result.prepareN_ = value;
        return this;
      }
      public Builder clearPrepareN() {
        result.hasPrepareN = false;
        result.prepareN_ = 0;
        return this;
      }
      
      // optional .Proposal acceptedPreviously = 2;
      public boolean hasAcceptedPreviously() {
        return result.hasAcceptedPreviously();
      }
      public paxos.Messages.Proposal getAcceptedPreviously() {
        return result.getAcceptedPreviously();
      }
      public Builder setAcceptedPreviously(paxos.Messages.Proposal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasAcceptedPreviously = true;
        result.acceptedPreviously_ = value;
        return this;
      }
      public Builder setAcceptedPreviously(paxos.Messages.Proposal.Builder builderForValue) {
        result.hasAcceptedPreviously = true;
        result.acceptedPreviously_ = builderForValue.build();
        return this;
      }
      public Builder mergeAcceptedPreviously(paxos.Messages.Proposal value) {
        if (result.hasAcceptedPreviously() &&
            result.acceptedPreviously_ != paxos.Messages.Proposal.getDefaultInstance()) {
          result.acceptedPreviously_ =
            paxos.Messages.Proposal.newBuilder(result.acceptedPreviously_).mergeFrom(value).buildPartial();
        } else {
          result.acceptedPreviously_ = value;
        }
        result.hasAcceptedPreviously = true;
        return this;
      }
      public Builder clearAcceptedPreviously() {
        result.hasAcceptedPreviously = false;
        result.acceptedPreviously_ = paxos.Messages.Proposal.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Promise)
    }
    
    static {
      defaultInstance = new Promise(true);
      paxos.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Promise)
  }
  
  public static final class AcceptRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use AcceptRequest.newBuilder() to construct.
    private AcceptRequest() {
      initFields();
    }
    private AcceptRequest(boolean noInit) {}
    
    private static final AcceptRequest defaultInstance;
    public static AcceptRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public AcceptRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paxos.Messages.internal_static_AcceptRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paxos.Messages.internal_static_AcceptRequest_fieldAccessorTable;
    }
    
    // required .Proposal proposal = 1;
    public static final int PROPOSAL_FIELD_NUMBER = 1;
    private boolean hasProposal;
    private paxos.Messages.Proposal proposal_;
    public boolean hasProposal() { return hasProposal; }
    public paxos.Messages.Proposal getProposal() { return proposal_; }
    
    private void initFields() {
      proposal_ = paxos.Messages.Proposal.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasProposal) return false;
      if (!getProposal().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProposal()) {
        output.writeMessage(1, getProposal());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProposal()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProposal());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static paxos.Messages.AcceptRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.AcceptRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.AcceptRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.AcceptRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.AcceptRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.AcceptRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.AcceptRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.AcceptRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.AcceptRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.AcceptRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(paxos.Messages.AcceptRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private paxos.Messages.AcceptRequest result;
      
      // Construct using paxos.Messages.AcceptRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new paxos.Messages.AcceptRequest();
        return builder;
      }
      
      protected paxos.Messages.AcceptRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new paxos.Messages.AcceptRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return paxos.Messages.AcceptRequest.getDescriptor();
      }
      
      public paxos.Messages.AcceptRequest getDefaultInstanceForType() {
        return paxos.Messages.AcceptRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public paxos.Messages.AcceptRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private paxos.Messages.AcceptRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public paxos.Messages.AcceptRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        paxos.Messages.AcceptRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof paxos.Messages.AcceptRequest) {
          return mergeFrom((paxos.Messages.AcceptRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(paxos.Messages.AcceptRequest other) {
        if (other == paxos.Messages.AcceptRequest.getDefaultInstance()) return this;
        if (other.hasProposal()) {
          mergeProposal(other.getProposal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              paxos.Messages.Proposal.Builder subBuilder = paxos.Messages.Proposal.newBuilder();
              if (hasProposal()) {
                subBuilder.mergeFrom(getProposal());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProposal(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .Proposal proposal = 1;
      public boolean hasProposal() {
        return result.hasProposal();
      }
      public paxos.Messages.Proposal getProposal() {
        return result.getProposal();
      }
      public Builder setProposal(paxos.Messages.Proposal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasProposal = true;
        result.proposal_ = value;
        return this;
      }
      public Builder setProposal(paxos.Messages.Proposal.Builder builderForValue) {
        result.hasProposal = true;
        result.proposal_ = builderForValue.build();
        return this;
      }
      public Builder mergeProposal(paxos.Messages.Proposal value) {
        if (result.hasProposal() &&
            result.proposal_ != paxos.Messages.Proposal.getDefaultInstance()) {
          result.proposal_ =
            paxos.Messages.Proposal.newBuilder(result.proposal_).mergeFrom(value).buildPartial();
        } else {
          result.proposal_ = value;
        }
        result.hasProposal = true;
        return this;
      }
      public Builder clearProposal() {
        result.hasProposal = false;
        result.proposal_ = paxos.Messages.Proposal.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:AcceptRequest)
    }
    
    static {
      defaultInstance = new AcceptRequest(true);
      paxos.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:AcceptRequest)
  }
  
  public static final class AcceptedProposal extends
      com.google.protobuf.GeneratedMessage {
    // Use AcceptedProposal.newBuilder() to construct.
    private AcceptedProposal() {
      initFields();
    }
    private AcceptedProposal(boolean noInit) {}
    
    private static final AcceptedProposal defaultInstance;
    public static AcceptedProposal getDefaultInstance() {
      return defaultInstance;
    }
    
    public AcceptedProposal getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paxos.Messages.internal_static_AcceptedProposal_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paxos.Messages.internal_static_AcceptedProposal_fieldAccessorTable;
    }
    
    // required .Proposal proposal = 1;
    public static final int PROPOSAL_FIELD_NUMBER = 1;
    private boolean hasProposal;
    private paxos.Messages.Proposal proposal_;
    public boolean hasProposal() { return hasProposal; }
    public paxos.Messages.Proposal getProposal() { return proposal_; }
    
    private void initFields() {
      proposal_ = paxos.Messages.Proposal.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasProposal) return false;
      if (!getProposal().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProposal()) {
        output.writeMessage(1, getProposal());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProposal()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProposal());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static paxos.Messages.AcceptedProposal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.AcceptedProposal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.AcceptedProposal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.AcceptedProposal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.AcceptedProposal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.AcceptedProposal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.AcceptedProposal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.AcceptedProposal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.AcceptedProposal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.AcceptedProposal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(paxos.Messages.AcceptedProposal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private paxos.Messages.AcceptedProposal result;
      
      // Construct using paxos.Messages.AcceptedProposal.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new paxos.Messages.AcceptedProposal();
        return builder;
      }
      
      protected paxos.Messages.AcceptedProposal internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new paxos.Messages.AcceptedProposal();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return paxos.Messages.AcceptedProposal.getDescriptor();
      }
      
      public paxos.Messages.AcceptedProposal getDefaultInstanceForType() {
        return paxos.Messages.AcceptedProposal.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public paxos.Messages.AcceptedProposal build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private paxos.Messages.AcceptedProposal buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public paxos.Messages.AcceptedProposal buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        paxos.Messages.AcceptedProposal returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof paxos.Messages.AcceptedProposal) {
          return mergeFrom((paxos.Messages.AcceptedProposal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(paxos.Messages.AcceptedProposal other) {
        if (other == paxos.Messages.AcceptedProposal.getDefaultInstance()) return this;
        if (other.hasProposal()) {
          mergeProposal(other.getProposal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              paxos.Messages.Proposal.Builder subBuilder = paxos.Messages.Proposal.newBuilder();
              if (hasProposal()) {
                subBuilder.mergeFrom(getProposal());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProposal(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .Proposal proposal = 1;
      public boolean hasProposal() {
        return result.hasProposal();
      }
      public paxos.Messages.Proposal getProposal() {
        return result.getProposal();
      }
      public Builder setProposal(paxos.Messages.Proposal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasProposal = true;
        result.proposal_ = value;
        return this;
      }
      public Builder setProposal(paxos.Messages.Proposal.Builder builderForValue) {
        result.hasProposal = true;
        result.proposal_ = builderForValue.build();
        return this;
      }
      public Builder mergeProposal(paxos.Messages.Proposal value) {
        if (result.hasProposal() &&
            result.proposal_ != paxos.Messages.Proposal.getDefaultInstance()) {
          result.proposal_ =
            paxos.Messages.Proposal.newBuilder(result.proposal_).mergeFrom(value).buildPartial();
        } else {
          result.proposal_ = value;
        }
        result.hasProposal = true;
        return this;
      }
      public Builder clearProposal() {
        result.hasProposal = false;
        result.proposal_ = paxos.Messages.Proposal.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:AcceptedProposal)
    }
    
    static {
      defaultInstance = new AcceptedProposal(true);
      paxos.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:AcceptedProposal)
  }
  
  public static final class Heartbeat extends
      com.google.protobuf.GeneratedMessage {
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat() {
      initFields();
    }
    private Heartbeat(boolean noInit) {}
    
    private static final Heartbeat defaultInstance;
    public static Heartbeat getDefaultInstance() {
      return defaultInstance;
    }
    
    public Heartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paxos.Messages.internal_static_Heartbeat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paxos.Messages.internal_static_Heartbeat_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static paxos.Messages.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static paxos.Messages.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static paxos.Messages.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static paxos.Messages.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static paxos.Messages.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(paxos.Messages.Heartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private paxos.Messages.Heartbeat result;
      
      // Construct using paxos.Messages.Heartbeat.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new paxos.Messages.Heartbeat();
        return builder;
      }
      
      protected paxos.Messages.Heartbeat internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new paxos.Messages.Heartbeat();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return paxos.Messages.Heartbeat.getDescriptor();
      }
      
      public paxos.Messages.Heartbeat getDefaultInstanceForType() {
        return paxos.Messages.Heartbeat.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public paxos.Messages.Heartbeat build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private paxos.Messages.Heartbeat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public paxos.Messages.Heartbeat buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        paxos.Messages.Heartbeat returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof paxos.Messages.Heartbeat) {
          return mergeFrom((paxos.Messages.Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(paxos.Messages.Heartbeat other) {
        if (other == paxos.Messages.Heartbeat.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:Heartbeat)
    }
    
    static {
      defaultInstance = new Heartbeat(true);
      paxos.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Heartbeat)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Envelope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Envelope_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PrepareRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PrepareRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Proposal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proposal_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Promise_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Promise_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AcceptRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptedProposal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AcceptedProposal_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Heartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Heartbeat_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proj/paxos/Messages.proto\032\024proj/RPCPro" +
      "tos.proto\">\n\010Envelope\022\023\n\004type\030\001 \002(\0162\005.Ty" +
      "pe\022\017\n\007payload\030\002 \002(\014\022\014\n\004pxId\030\003 \001(\005\"\033\n\016Pre" +
      "pareRequest\022\t\n\001n\030\001 \002(\005\"0\n\010Proposal\022\t\n\001n\030" +
      "\001 \002(\005\022\031\n\001v\030\002 \002(\0132\016.CommitAttempt\"B\n\007Prom" +
      "ise\022\020\n\010prepareN\030\001 \002(\005\022%\n\022acceptedPreviou" +
      "sly\030\002 \001(\0132\t.Proposal\",\n\rAcceptRequest\022\033\n" +
      "\010proposal\030\001 \002(\0132\t.Proposal\"/\n\020AcceptedPr" +
      "oposal\022\033\n\010proposal\030\001 \002(\0132\t.Proposal\"\013\n\tH" +
      "eartbeat*b\n\004Type\022\023\n\017PREPARE_REQUEST\020\000\022\022\n",
      "\016ACCEPT_REQUEST\020\001\022\013\n\007PROMISE\020\002\022\025\n\021ACCEPT" +
      "ED_PROPOSAL\020\003\022\r\n\tHEARTBEAT\020\004*X\n\004Role\022\014\n\010" +
      "PROPOSER\020\000\022\014\n\010ACCEPTOR\020\001\022\013\n\007LEARNER\020\002\022\013\n" +
      "\007MONITOR\020\004\022\014\n\010TXSERVER\020\005\022\014\n\010TXCLIENT\020\006B\007" +
      "\n\005paxos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Envelope_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Envelope_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Envelope_descriptor,
              new java.lang.String[] { "Type", "Payload", "PxId", },
              paxos.Messages.Envelope.class,
              paxos.Messages.Envelope.Builder.class);
          internal_static_PrepareRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PrepareRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PrepareRequest_descriptor,
              new java.lang.String[] { "N", },
              paxos.Messages.PrepareRequest.class,
              paxos.Messages.PrepareRequest.Builder.class);
          internal_static_Proposal_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Proposal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Proposal_descriptor,
              new java.lang.String[] { "N", "V", },
              paxos.Messages.Proposal.class,
              paxos.Messages.Proposal.Builder.class);
          internal_static_Promise_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Promise_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Promise_descriptor,
              new java.lang.String[] { "PrepareN", "AcceptedPreviously", },
              paxos.Messages.Promise.class,
              paxos.Messages.Promise.Builder.class);
          internal_static_AcceptRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_AcceptRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AcceptRequest_descriptor,
              new java.lang.String[] { "Proposal", },
              paxos.Messages.AcceptRequest.class,
              paxos.Messages.AcceptRequest.Builder.class);
          internal_static_AcceptedProposal_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_AcceptedProposal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AcceptedProposal_descriptor,
              new java.lang.String[] { "Proposal", },
              paxos.Messages.AcceptedProposal.class,
              paxos.Messages.AcceptedProposal.Builder.class);
          internal_static_Heartbeat_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_Heartbeat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Heartbeat_descriptor,
              new java.lang.String[] { },
              paxos.Messages.Heartbeat.class,
              paxos.Messages.Heartbeat.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.RPCProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
